import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { HeaderComponent } from "./Header";

import "@/app/ui/globals.css";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "User app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider user={{ username: 'lox', isLoggedIn: true }}>
      <html lang="en">
        <body className={inter.className}>
          <HeaderComponent></HeaderComponent>
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
